version: "3"

services:

  app:
    build:
      context: ./node
    container_name: app_node
    command: dockerize -wait tcp://db_node:3306 -timeout 20s node index.js
    tty: true
    volumes:
      - ./node:/usr/src/app
    networks:
      - nodenet
    depends_on:
      - db
  
  nginx:
    build:
      context: ./nginx
    container_name: nginx_node
    tty: true
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    build:
      context: ./mysql
    container_name: db_node
    command: --innodb-use-native-aio=0 --default-authentication-plugin=mysql_native_password
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet


networks:
  nodenet:
    driver: bridge