version: "3"

services:

  app:
    build:
      context: ./node
    container_name: app_node
    entrypoint: dockerize -wait tcp://db_node:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    tty: true
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - nodenet
    depends_on:
      - db
  
  nginx:
    build:
      context: ./nginx
    container_name: nginx_node
    entrypoint: dockerize -wait tcp://app_node:3000 -timeout 20s /docker-entrypoint.sh
    command: nginx -g 'daemon off;'
    tty: true
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    build:
      context: ./mysql
    container_name: db_node
    command: --innodb-use-native-aio=0 --default-authentication-plugin=mysql_native_password
    tty: true
    restart: always
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet


networks:
  nodenet:
    driver: bridge